// ============================================================================
// Postgres 存储层（pg Pool，异步 API）：建库建表 + 语句导出（阶段1 单实例产品化）
// ----------------------------------------------------------------------------
// 与原 SQLite 版的对应关系：
//   - 同步 .get()/.all()/.run() → 异步函数，返回 rows[0] / rows；
//   - chat_messages.seq 自增 → INTEGER GENERATED ALWAYS AS IDENTITY；
//   - tags / meta TEXT(JSON 字符串) → JSONB（读出即对象，写入走 jsonParam）；
//   - ON CONFLICT 语义两库一致，upsert/grant 语句原样平移。
// 惯例：
//   - 启动首次查询前先执行 SCHEMA（CREATE TABLE IF NOT EXISTS，幂等）；
//   - schemaReady 为全局初始化 promise，每个查询先 await 它（失败在调用处抛出）。
// ============================================================================

import pg from 'pg'
import { config } from '../config.js'

const pool = new pg.Pool({ connectionString: config.pg.url, max: 10 })

const SCHEMA = `
CREATE TABLE IF NOT EXISTS users (
  id         TEXT PRIMARY KEY,                 -- UUID
  username   TEXT UNIQUE NOT NULL,             -- 登录名（唯一）
  pass_hash  TEXT NOT NULL,                    -- scrypt 哈希（salt:hash）
  role       TEXT NOT NULL DEFAULT 'member',   -- member | admin
  dept       TEXT NOT NULL DEFAULT '',         -- 部门编码（dept 密级判定依据）
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS documents (
  id             TEXT PRIMARY KEY,              -- UUID，同时是 Qdrant payload.docId
  filename       TEXT NOT NULL,
  size           INTEGER NOT NULL,
  hash           TEXT UNIQUE NOT NULL,          -- SHA-256 内容级去重
  chunks         INTEGER NOT NULL DEFAULT 0,
  status         TEXT NOT NULL DEFAULT 'ready', -- pending/processing/ready/failed
  error          TEXT,
  path           TEXT,
  user_id        TEXT NOT NULL DEFAULT '',      -- owner（M5）
  classification TEXT NOT NULL DEFAULT 'public',-- public/dept/private（M10）
  tags           JSONB NOT NULL DEFAULT '[]'::jsonb, -- 白名单标签数组（M10）
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_documents_user ON documents(user_id);
CREATE INDEX IF NOT EXISTS idx_documents_tags ON documents USING GIN (tags);

CREATE TABLE IF NOT EXISTS sessions (
  id             TEXT PRIMARY KEY,
  title          TEXT NOT NULL,
  user_id        TEXT NOT NULL DEFAULT '',      -- M5 归属
  summary        TEXT NOT NULL DEFAULT '',      -- M4 滚动摘要
  summarized_seq INTEGER NOT NULL DEFAULT 0,    -- seq 水位断点（删除免疫）
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);

CREATE TABLE IF NOT EXISTS chat_messages (
  seq        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 全局自增，回放/压缩水位依据（BY DEFAULT：迁移可显式插值）
  session_id TEXT NOT NULL,
  role       TEXT NOT NULL,                    -- user | assistant
  content    TEXT NOT NULL,
  meta       JSONB,                            -- {sources, steps, usage, stopReason}
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_chat_messages_session ON chat_messages(session_id);

CREATE TABLE IF NOT EXISTS doc_grants (
  doc_id  TEXT NOT NULL,
  user_id TEXT NOT NULL,
  PRIMARY KEY (doc_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_grants_user ON doc_grants(user_id);

-- M12 多实例：抢占时间戳（宕机后由 stale 回收判定"卡死"的 processing）
ALTER TABLE documents ADD COLUMN IF NOT EXISTS processing_since TIMESTAMPTZ;
-- M17 领域包：文档归属集合（core=agentic_docs / 领域=rag_<pack>）+ 语料治理三字段
ALTER TABLE documents ADD COLUMN IF NOT EXISTS collection TEXT NOT NULL DEFAULT 'agentic_docs';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS source_url TEXT NOT NULL DEFAULT '';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS doc_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS deprecated BOOLEAN NOT NULL DEFAULT false;
-- M18 语料时效：版本组标识（同组检索只保留最高 doc_version）+ 生效日期（ISO 日期串，展示/进上下文）
ALTER TABLE documents ADD COLUMN IF NOT EXISTS doc_key TEXT NOT NULL DEFAULT '';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS effective_date TEXT NOT NULL DEFAULT '';
-- M14 无状态鉴权：token_ver 进 JWT（改角色 +1 即刻失效旧 token）；refresh 单活哈希（旋转复用）
ALTER TABLE users ADD COLUMN IF NOT EXISTS token_ver INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS refresh_hash TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS refresh_exp TIMESTAMPTZ;
`

// 启动即初始化 schema；挂 no-op catch 防早期 unhandledRejection，真实错误由首个查询处抛出
// 导出给迁移脚本等外部工具 await（确保建表先于数据导入）
export const schemaReady = pool.query(SCHEMA)
schemaReady.catch(() => { })

async function q(text, params = []) {
  await schemaReady
  return pool.query(text, params)
}

// JSONB 参数：数组/对象 → JSON 字符串（pg 对 JS 数组默认序列化成 PG 数组而非 JSON，需显式转）
const jsonParam = (v) => (typeof v === 'string' ? v : JSON.stringify(v ?? []))

// ---- users：登录账号（AUTH_USERS 预置播种；M10 起带角色/部门）----
// 播种语义：密码只写一次（已存在用户不覆盖）；role/dept 每次启动按 env 刷新
export async function upsertUser(id, username, passHash, role, dept) {
  await q(
    `INSERT INTO users (id, username, pass_hash, role, dept) VALUES ($1, $2, $3, $4, $5)
     ON CONFLICT(username) DO UPDATE SET role = excluded.role, dept = excluded.dept`,
    [id, username, passHash, role, dept]
  )
}

// ---- M14 无状态鉴权：token_ver 自增（旧 access token 的 ver 立即对不上 → 401）----
export async function bumpUserTokenVer(id) {
  const { rows } = await q('UPDATE users SET token_ver = token_ver + 1 WHERE id = $1 RETURNING token_ver', [id])
  return rows[0]?.token_ver ?? 0
}

// refresh 单活模型：同一用户仅一个有效 refresh token（登录/刷新时覆盖，登出/失效时置空）
export async function setRefreshToken(id, hash, exp) {
  await q('UPDATE users SET refresh_hash = $2, refresh_exp = $3 WHERE id = $1', [id, hash, exp])
}

// refresh 旋转查找：sha256(refreshToken) → 用户行（无行 = token 无效或已被旋转覆盖）
export async function getUserByRefreshHash(hash) {
  const { rows } = await q(
    'SELECT id, username, role, dept, token_ver, refresh_hash, refresh_exp FROM users WHERE refresh_hash = $1',
    [hash]
  )
  return rows[0] ?? null
}
export async function getUserByName(username) {
  return (await q('SELECT * FROM users WHERE username = $1', [username])).rows[0]
}
export async function getUserById(id) {
  return (await q('SELECT * FROM users WHERE id = $1', [id])).rows[0]
}
export async function listUsers() {
  return (await q('SELECT id, username, role, dept, created_at FROM users ORDER BY created_at')).rows
}
export async function updateUserMeta(role, dept, id) {
  await q('UPDATE users SET role = $1, dept = $2 WHERE id = $3', [role, dept, id])
}
// 历史文档归属回填：M5 升级前入库的文档 user_id='' 划给首个预置用户，返回受影响行数
export async function backfillDocsToUser(userId) {
  const r = await q("UPDATE documents SET user_id = $1 WHERE user_id = ''", [userId])
  return r.rowCount
}

// ---- documents：摄取队列 + 文档管理（M10 起带密级/标签/授权；M17 起带集合/语料治理字段）----
// extra（M17/M18 可选）：{ collection, sourceUrl, docVersion, deprecated, docKey, effectiveDate }
// ——手动上传不传走缺省；docKey 为版本组标识（core 缺省 filename，领域包 = sourceUrl）
export async function insertDoc(id, filename, size, hash, chunks, status, error, path, userId, classification, tags, extra = {}) {
  await q(
    `INSERT INTO documents (id, filename, size, hash, chunks, status, error, path, user_id, classification, tags,
                            collection, source_url, doc_version, deprecated, doc_key, effective_date)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11::jsonb, $12, $13, $14, $15, $16, $17)`,
    [id, filename, size, hash, chunks, status, error, path, userId, classification, jsonParam(tags),
      extra.collection || 'agentic_docs', extra.sourceUrl ?? '', extra.docVersion ?? 1, extra.deprecated ?? false,
      extra.docKey ?? '', extra.effectiveDate ?? '']
  )
}
// 可见列表：本人 ∪ public ∪ 同部门(dept) ∪ 被显式授权；admin 走 listDocsAll 全量
export async function listDocsVisible(userId, dept) {
  return (
    await q(
      `SELECT d.*, u.username AS owner_name, u.dept AS owner_dept
       FROM documents d LEFT JOIN users u ON u.id = d.user_id
       WHERE d.user_id = $1
          OR d.classification = 'public'
          OR (d.classification = 'dept' AND $2 != '' AND u.dept = $2)
          OR d.id IN (SELECT doc_id FROM doc_grants WHERE user_id = $1)
       ORDER BY d.created_at DESC`,
      [userId, dept]
    )
  ).rows
}
export async function listDocsAll() {
  return (
    await q(
      `SELECT d.*, u.username AS owner_name, u.dept AS owner_dept
       FROM documents d LEFT JOIN users u ON u.id = d.user_id
       ORDER BY d.created_at DESC`
    )
  ).rows
}
export async function updateDocMeta(classification, tags, id) {
  await q('UPDATE documents SET classification = $1, tags = $2::jsonb WHERE id = $3', [classification, jsonParam(tags), id])
}
export async function getDoc(id) {
  return (await q('SELECT * FROM documents WHERE id = $1', [id])).rows[0]
}
export async function getDocByHash(hash) {
  return (await q('SELECT * FROM documents WHERE hash = $1', [hash])).rows[0]
}
// M17 连接器：按溯源 URL 找同源文档（内容变更时做版本化替换）
export async function getDocBySourceUrl(sourceUrl) {
  return (await q('SELECT * FROM documents WHERE source_url = $1 ORDER BY created_at DESC LIMIT 1', [sourceUrl])).rows[0]
}
// M18 版本化替换：按版本组标识取最新行（同组多版本时 doc_version 最高者；旧版本化替换的基准）
export async function getLatestDocByKey(collection, docKey) {
  if (!collection || !docKey) return null
  return (
    await q(
      'SELECT * FROM documents WHERE collection = $1 AND doc_key = $2 ORDER BY doc_version DESC, created_at DESC LIMIT 1',
      [collection, docKey]
    )
  ).rows[0] ?? null
}
export async function deleteDocRow(id) {
  await q('DELETE FROM documents WHERE id = $1', [id])
}
// 状态更新：(status, error, id)；worker 占坑传 ('processing', null)，失败传 ('failed', errMsg)
// processing 时同步盖 processing_since 时间戳（stale 回收依据），离开 processing 置空
export async function setDocStatus(status, error, id) {
  await q(
    `UPDATE documents SET status = $1, error = $2,
       processing_since = CASE WHEN $1 = 'processing' THEN now() END
     WHERE id = $3`,
    [status, error, id]
  )
}
export async function setDocChunks(chunks, id) {
  await q('UPDATE documents SET chunks = $1 WHERE id = $2', [chunks, id])
}
// 摄取队列抢占（M12 多实例）：事务内 SELECT ... FOR UPDATE SKIP LOCKED 抢占最老 pending，
// 抢到即置 processing（含 processing_since）；并发的其他实例会跳过该行直接抢下一条/空手而归
export async function claimNextPendingDoc() {
  const client = await pool.connect()
  try {
    await client.query('BEGIN')
    const sel = await client.query(
      "SELECT * FROM documents WHERE status = 'pending' ORDER BY created_at ASC LIMIT 1 FOR UPDATE SKIP LOCKED"
    )
    const doc = sel.rows[0]
    if (!doc) {
      await client.query('COMMIT')
      return undefined
    }
    await client.query(
      "UPDATE documents SET status = 'processing', processing_since = now() WHERE id = $1",
      [doc.id]
    )
    await client.query('COMMIT')
    return doc
  } catch (e) {
    await client.query('ROLLBACK').catch(() => { })
    throw e
  } finally {
    client.release()
  }
}
// 宕机回收：仅回收"卡在 processing 超过 30 分钟"的文档（多实例下误回收他实例在途任务的最小风险窗口）
export async function resetProcessing() {
  await q(
    "UPDATE documents SET status = 'pending', processing_since = NULL WHERE status = 'processing' AND processing_since < now() - interval '30 minutes'"
  )
}

// ---- doc_grants：显式授权（private/dept 文档可单独授权给指定用户）----
export async function listGrantsByDoc(docId) {
  return (await q('SELECT user_id FROM doc_grants WHERE doc_id = $1', [docId])).rows
}
export async function listGrantsForUser(userId) {
  return (await q('SELECT doc_id FROM doc_grants WHERE user_id = $1', [userId])).rows
}
export async function grantDoc(docId, userId) {
  await q('INSERT INTO doc_grants (doc_id, user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING', [docId, userId])
}
export async function revokeGrant(docId, userId) {
  await q('DELETE FROM doc_grants WHERE doc_id = $1 AND user_id = $2', [docId, userId])
}
export async function deleteGrantsByDoc(docId) {
  await q('DELETE FROM doc_grants WHERE doc_id = $1', [docId])
}

// ---- sessions：会话管理（M5 起按 user_id 隔离）----
export async function insertSession(id, title, userId) {
  await q('INSERT INTO sessions (id, title, user_id) VALUES ($1, $2, $3)', [id, title, userId])
}
export async function listSessionsByUser(userId) {
  return (await q('SELECT * FROM sessions WHERE user_id = $1 ORDER BY created_at DESC', [userId])).rows
}
export async function getSession(id) {
  return (await q('SELECT * FROM sessions WHERE id = $1', [id])).rows[0]
}
export async function deleteSession(id) {
  await q('DELETE FROM sessions WHERE id = $1', [id])
}
export async function deleteSessionMsgs(sessionId) {
  await q('DELETE FROM chat_messages WHERE session_id = $1', [sessionId])
}

// ---- chat_messages：消息读写 ----
export async function insertMsg(sessionId, role, content, meta) {
  await q('INSERT INTO chat_messages (session_id, role, content, meta) VALUES ($1, $2, $3, $4::jsonb)', [
    sessionId, role, content, meta == null ? null : jsonParam(meta),
  ])
}
// 按 seq 升序：保证多轮对话顺序正确（slice(-20) 取最近窗口）
export async function listMsgs(sessionId) {
  return (await q('SELECT * FROM chat_messages WHERE session_id = $1 ORDER BY seq ASC', [sessionId])).rows
}
// 记忆回放：断点之后的所有消息（= 固定窗口 + 未压缩真空区，零丢失且上界可控）
export async function listAfterSeq(sessionId, seq) {
  return (await q('SELECT * FROM chat_messages WHERE session_id = $1 AND seq > $2 ORDER BY seq ASC', [sessionId, seq])).rows
}
// 窗口起点：最近 N 条里最早一条的 seq（压缩边界：断点之前的都要进摘要）
export async function windowStartSeq(sessionId, windowSize) {
  return (
    await q(
      'SELECT MIN(seq)::int AS s FROM (SELECT seq FROM chat_messages WHERE session_id = $1 ORDER BY seq DESC LIMIT $2) t',
      [sessionId, windowSize]
    )
  ).rows[0]
}
// 待压缩数：断点与窗口起点之间的消息条数（攒批判断依据）
export async function countPending(sessionId, from, to) {
  return (
    await q('SELECT COUNT(*)::int AS n FROM chat_messages WHERE session_id = $1 AND seq > $2 AND seq <= $3', [sessionId, from, to])
  ).rows[0]
}
// 取待压缩的早期消息（断点 → 窗口起点]，用于增量摘要
export async function listPending(sessionId, from, to) {
  return (
    await q('SELECT * FROM chat_messages WHERE session_id = $1 AND seq > $2 AND seq <= $3 ORDER BY seq ASC', [sessionId, from, to])
  ).rows
}

// ---- sessions：记忆压缩（滚动摘要，seq 水位断点）----
export async function getMemory(sessionId) {
  return (await q('SELECT summary, summarized_seq FROM sessions WHERE id = $1', [sessionId])).rows[0]
}
export async function updateMemory(summary, seq, sessionId) {
  await q('UPDATE sessions SET summary = $1, summarized_seq = $2 WHERE id = $3', [summary, seq, sessionId])
}

/** 优雅退出时关闭连接池 */
export async function closePool() {
  await pool.end()
}
